version: '3'

services:
  redis:
    image: redis:latest
    ports:
      - '6379:6379'
  api_management:
    build: proxy_api/.
    environment:
      REDIS_HOST: 'redis'
      LOGGING_LEVEL: 'DEBUG'
    command: gunicorn --bind :80 --workers 1 --threads 2 --timeout 0 app:app
    ports:
      - "8080:80"
    depends_on:
      - redis
  maintenance:
    build: invalid_proxy_watcher/.
    environment:
      REDIS_HOST: 'redis'
      HOURS_TO_BAN: '6'
      LOGGING_LEVEL: 'DEBUG'
    command: python main.py
    depends_on:
      - redis
